// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCakjhpbH8ajp1fMTXeBZfxT-_txoj094A',
    appId: '1:791673854689:web:44f52e0c327c1edea1b5a0',
    messagingSenderId: '791673854689',
    projectId: 'todo-ef939',
    authDomain: 'todo-ef939.firebaseapp.com',
    storageBucket: 'todo-ef939.firebasestorage.app',
    measurementId: 'G-VGKGMP3359',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqr4CLnvvpC7ajgb0BpTZj0dMCwF_Vtpc',
    appId: '1:791673854689:android:615d4877f2698d50a1b5a0',
    messagingSenderId: '791673854689',
    projectId: 'todo-ef939',
    storageBucket: 'todo-ef939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBnVzz0lpi0d68R6r_iyi12wD2k0SiToA',
    appId: '1:791673854689:ios:523803334ab64270a1b5a0',
    messagingSenderId: '791673854689',
    projectId: 'todo-ef939',
    storageBucket: 'todo-ef939.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBnVzz0lpi0d68R6r_iyi12wD2k0SiToA',
    appId: '1:791673854689:ios:0ee59147db1f4660a1b5a0',
    messagingSenderId: '791673854689',
    projectId: 'todo-ef939',
    storageBucket: 'todo-ef939.firebasestorage.app',
    iosBundleId: 'e',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCakjhpbH8ajp1fMTXeBZfxT-_txoj094A',
    appId: '1:791673854689:web:c48e5ff5ef4b341ea1b5a0',
    messagingSenderId: '791673854689',
    projectId: 'todo-ef939',
    authDomain: 'todo-ef939.firebaseapp.com',
    storageBucket: 'todo-ef939.firebasestorage.app',
    measurementId: 'G-M8JK4DH922',
  );
}
